### ISSUE TITLE
Opportunity to shorten the code

### ISSUE THREAD

**Issue by michaelKurowski** [jakubbokwa/exercise-website#14]
https://github.com/jakubbokwa/exercise-website/blob/3d3adc5c8b1831c2aedf9827017c11eca341fe58/app.js#L115-L117

Just 

`companies.find(company => company.code === companyCode)`

Would be also worth naming `companyCode` differently to differentiate between these two.

**Comment by jakubbokwa** [comment]
Issue resolved
