### ISSUE TITLE
Too many comments

### ISSUE THREAD

**Issue by michaelKurowski** [jakubbokwa/exercise-website#3]
I appreciate the efforts but too many comments is also bad.
A programmer reading your code already sees what it does, if you feel that there's a need to explain what the code does by commenting on it, there's a chance that you need to refactor the code as it might be unclear.

Comments might be needed to explain the `why` of the code, i.e. when we need to perform a hack, a workaround for a browser bug, our dependency's bug, or any other reason that might make the cause for us performing some actions unintuitive and unclear. Comments might be also useful when exposing a set of functions as an API. 

Recommended reads:
https://itnext.io/what-makes-a-good-code-comment-5267debd2c24
https://www.freecodecamp.org/news/code-comments-the-good-the-bad-and-the-ugly-be9cc65fbf83/

**Comment by jakubbokwa** [comment]
Thank you for the remark. I have read the included articles and removed the comments which were obvious.
