### ISSUE TITLE
A bit too smart 

### ISSUE THREAD

**Issue by michaelKurowski** [jakubbokwa/exercise-website#4]
https://github.com/jakubbokwa/exercise-website/blob/3d3adc5c8b1831c2aedf9827017c11eca341fe58/app.js#L17

It's better to write sometimes 2 or more lines and make them clear, instead of doing stuff that might be a bit convoluted.
Split this line into two

**Comment by krskibin** [comment]
Let's even keep that in one line. You can just assign `data = {sth}`, or return those data. I would go with `return { customers: customersData, companies: companiesData }`.
